"""Service-side ports for serialized hardware and remapping ownership."""

from typing import Protocol

from naga_control.domain.hardware import DeviceMode, HardwareState, SettingsFailure
from naga_control.domain.profiles import Profile
from naga_control.ports.hardware import NagaTopology


class ServiceHardwareWorker(Protocol):
    async def start(self) -> None: ...

    def mark_topology_stale(self) -> None: ...

    async def rescan(self, connections: tuple[NagaTopology, ...]) -> HardwareState: ...

    async def refresh_state(self) -> HardwareState: ...

    async def read_device_mode(self) -> DeviceMode: ...

    async def set_device_mode(self, mode: DeviceMode) -> DeviceMode: ...

    async def apply_profile_settings(
        self, profile: Profile
    ) -> tuple[HardwareState, tuple[SettingsFailure, ...]]: ...

    async def stop(self) -> None: ...


class RemappingSession(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    def release_all(self) -> None: ...
